### ISSUE TITLE
Error when adding Intergas Incomfort Gateway

### ISSUE THREAD

**Issue by Patrique70** [sorted-bits/intergas-homey#1]
When I want to add my Incomfort Gateway I get an error. See my screenshots. After login I can choose 2 “Gateways”, maybe this has to do with the fact that I have an Intergas Xtreme + an Intergas Xtend (hybrid heatpump)? Even if I deselect one of them, I still get the error: "Invalid setting type! Got number but expected string (text) for updateInterval"

![IMG_6908](https://github.com/sorted-bits/intergas-homey/assets/78215105/dd5d606c-5ea4-4cbc-800b-05a0224717ce)
![IMG_6909](https://github.com/sorted-bits/intergas-homey/assets/78215105/56acbcd3-b3e4-49b5-b37e-9015f7ad627e)
![IMG_6907](https://github.com/sorted-bits/intergas-homey/assets/78215105/a1220296-fbea-4d71-a8ac-2afb4ceebee0)

**Comment by sorted-bits** [comment]
Fixed in latest release. Thanks for taking the time to mention it.
