### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by BasKni** [sorted-bits/intergas-homey#2]
Is there any manual which describes how to login?

What is the gateway host, is that the IP-adress I have for my gateway in my Comfort Touch app?

Which username? The one I use for login into the Comfort Touch app or standard 'Admin'?

Which password, the one for the comfort touch app or the one on the back of the gateway?

Thanks in advance!

**Comment by sorted-bits** [comment]
Just for documentation, I think I already answered on the community forum:

The host is the IP address of your Gateway, this can usually be found in your router.
The username is 'admin'.
The password is on the back of the gateway device.
